### ISSUE TITLE
Import GPX data and extract GPX data in photos

### ISSUE THREAD

**Issue by Simmonslin** [tpemartin/109-2-app101#36]
請將所蒐集的 GPX 資訊加入 readGPX( ) 中，轉換成 DataFrame，並輸出路線圖

(GPX , 圖片上傳至 : https://drive.google.com/drive/u/0/folders/18-yd_0LF-oh5wk8uIVgY1oCWGMTIN2zN)

同時也能嘗試取出拍攝相片中的座標資訊 (照片是另外拍攝的，不與蒐集的 GPX 數據同步)

readGPX( )  usage :  https://plotkml.r-forge.r-project.org/readGPX.html

之前一直忽略，請大家在使用raedGPX()前下載 plotKML 套件
( 這次並無指派，大家有空就盡量嘗試 )

**Comment by Simmonslin** [comment]
路線圖輸出範例 :
[Graph_1.docx](https://github.com/tpemartin/109-2-app101/files/6310972/Graph_1.docx)

**Comment by schaof** [comment]
### 記得加上 library(leaflet) 
```{r}
library(leaflet)
fieldtrip$create_map(heritageData)
fieldtrip$show_path(df_gpx)
```

**Comment by schaof** [comment]
**這裡有介紹提取圖片資訊**
https://www.r-bloggers.com/2016/11/extracting-exif-data-from-photos-using-r/

**Comment by schaof** [comment]
好像不是很簡單@@
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/field_trip.Rmd

**Comment by Simmonslin** [comment]
建議各位在使用前先了解GPS資料的基本架構
網址 : https://zh.wikipedia.org/wiki/GPX

**Comment by Simmonslin** [comment]
需用到 Google Cloud API
https://github.com/Simmonslin/109-2-app101/blob/main/weekly_progress/frank/readGPX.Rmd

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/433ffdbf75ace9ed61e9374e38b6134dcffeddb8/weekly_progress/jilu/field_trip.Rmd#L26-L61
