### ISSUE TITLE
Process price_data

### ISSUE THREAD

**Issue by schaof** [tpemartin/109-2-app101#37]
將 df_inflation_long0 整理成以下 :
1. df_inflation_long_subcategories
2. df_inflation_long_total

Note: df_inflation_long_subcategories中"項目"的level要按照順序，
          可以用最後畫出的圖檢視
 
 ( 這次並無指派，大家有空就盡量嘗試 )

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/price_data.Rmd

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/9724d77421d46155ee1cd860f69aab4e55ef07d7/weekly_progress/jilu/price_data.Rmd#L21-L44

**Comment by yuhong69** [comment]
https://github.com/yuhong69/109-2-app101/blob/main/weekly_progress/yuhong/04-14-price_data.Rmd
