### ISSUE TITLE
中文版數字大小排列

### ISSUE THREAD

**Issue by Simmonslin** [tpemartin/109-2-app101#47]
此任務並無指派，大家可在弄完其他兩項 issue 後再來嘗試

需要的檔案 : process_chineseEnumerates.Rmd

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/chinese_enumerate.Rmd#L52
好像寫得有點複雜

**Comment by yuhong69** [comment]
https://github.com/yuhong69/109-2-app101/blob/main/weekly_progress/yuhong/05-01-process_chineseEnumerates.Rmd#L195

我的是暴力破解法？不會迴圈，好像也不能 map 中 map...

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/a2508835fb5a6555dd81b8f9bde6de467f7549a6/weekly_progress/jilu/process_chineseEnumerates.Rmd#L47
