### ISSUE TITLE
劃分難易度並依序做出不同維度拼圖

### ISSUE THREAD

**Issue by Simmonslin** [tpemartin/109-2-app101#48]
先將難易度劃分為簡單、普通、困難，並依序做出 3x3 、5x5、9x9拼圖
此為之前 Puzzle.Rmd 任務延伸

任務指派 : @chao87119 

其他人: 輔助角色

所需檔案 :Puzzle.Rmd, guess_heritage.Rmd

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/guess_heritage.Rmd
