### ISSUE TITLE
處理古蹟資料時間

### ISSUE THREAD

**Issue by schaof** [tpemartin/109-2-app101#58]
將古蹟歷史資料中，非以正規西元形式呈現的時間，轉為西元時間(1xxx)表示

目前包含 :  1. 民國XX      2. 中文西元年份      3. 日治時期

負責人 :  @Simmonslin  @want180

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/selectHeritage_byTime_inputInconsistencyProblem.Rmd#L44
資料裡還有一些其他的，不過我就沒有特別處理了

**Comment by Simmonslin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/Simmons/change_time.Rmd
大部分資料有做更正
