### ISSUE TITLE
古蹟資料時間處理(ii)

### ISSUE THREAD

**Issue by schaof** [tpemartin/109-2-app101#64]
將 https://github.com/tpemartin/109-2-app101/blob/main/R/chinese.R 中的函數以自己的版本完成，
並匯入之前 #58 的程式中，將 #58 的程式縮短
(Note: function中會重複用到的部分，可以寫成helper functions，置於最下方)

參考 : #58 , #55 
           https://github.com/tpemartin/109-2-app101/blob/main/R/chinese.R
           
負責人:  @chao87119  @Simmonslin  @yuhong69 @jilufu @want180

**Comment by yuhong69** [comment]
https://github.com/yuhong69/109-2-app101/blob/main/weekly_progress/yuhong/05-14-selectHeritage_byTime_inputInconsistencyProblem.Rmd

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/chinese.R
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/selectHeritage_byTime_inputInconsistencyProblem(ii).Rmd

**Comment by Simmonslin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/Simmons/change_time_function.Rmd

**Comment by tpemartin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/martin/selectHeritage_byTime_inputInconsistencyProblem_solution.Rmd

**Comment by tpemartin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/pipe_example.R
