### ISSUE TITLE
後端app功能設計 

### ISSUE THREAD

**Issue by Simmonslin** [tpemartin/109-2-app101#76]
1. show by county :  先選擇城市後 ( 例如台北市後 )，會出現台北市內的古蹟，跟之前的特定時間篩選任務類似，並將使用者的 
                                 搜尋結果儲存並回傳到 user 內。
   參考 :  #49 

2. play puzzle :  選擇play puzzle後，玩家能夠拼圖是哪個古蹟，並記錄下以下資料 (參考資料: #48  #27 )
 
                          1. 玩家開始遊戲的國際標準時間
                          2.  正確答案的caseID
                          3.  題目選項的 caseID
                          4.  玩家選擇的 caseID

3. check in:  假定一組前端回傳經緯度數字，並檢查該組經緯度是否在任何古蹟100公尺內，是的話
                    ，儲存使用者check in 的 國際標準時間，並儲存最靠近古蹟的caseId，否的化則回傳 NULL值。並將資料存 
                    在USER中。

                   (sp::spDistsN1 可計算距離)

4.  track:  當使用者在前端打開 track 選項，使用者手機將能追蹤GPS定位，並儲存下列資料。
        
               1. timestamp=date of visit  ( 各點時間 OR 起點終點時間)
               2. 軌跡(各點經緯度)
               3. 參訪古蹟的caseID

任務指派:    show by county : @jilufu  @Simmonslin 
          
 play puzzle : @want180  @chao87119  
 
 checkIN :  @yuhong69  @chao87119  @Simmonslin 
 
 track :  @yuhong69 

模板(含架構): https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/backend_template.R
請大家將自己負責的部分完成後，填入<- 右方空缺部分即可            

上述若有任何錯誤請直接更正

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/backend.R#L62
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/puzzle.R

**Comment by Simmonslin** [comment]
https://github.com/Simmonslin/109-2-app101/blob/main/weekly_progress/return_caseID.R

**Comment by yuhong69** [comment]
我是負責 3、4
4 有用到 3
不過跑出來 7 筆資料只有 check 到「臺北放送局、三峽庄役廠、三峽祖師廟」
不排除做錯 :)
https://github.com/yuhong69/109-2-app101/blob/main/weekly_progress/yuhong/05-27-backend.R#L71

**Comment by Simmonslin** [comment]
任務1 :
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/Simmons/show_county.R

任務4 :
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/Simmons/tracks_collection.R

**Comment by want180** [comment]
https://github.com/want180/109-2-app101/blob/main/weekly_progress/want180/play_puzzle.Rmd
半完成的程式碼....最後不知道要怎麼樣才會符合magick_image的型態所以跑不出來

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/537b0dc0b072eea48c96dca1d7b9a8af03d2dd1b/weekly_progress/jilu/backend.R#L36

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/af5cc8525a1ef5b35394badf3bfcf274f1eb090a/weekly_progress/jilu/backend.R#L36

**Comment by tpemartin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/martin/heritage_martin.R
