### ISSUE TITLE
架構與模板 (暫定)

### ISSUE THREAD

**Issue by schaof** [tpemartin/109-2-app101#77]
架構 :
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/stucture.R

模板 :
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/backend_template.R

我稍晚跟 @Simmonslin  討論之後會確定一個版本
並更新 #76 的資訊

**Comment by Simmonslin** [comment]
https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/Simmons/define_configuration.Rmd
