### ISSUE TITLE
CPI

### ISSUE THREAD

**Issue by schaof** [tpemartin/109-2-app101#85]
運用dplyr套件，完成以下三個任務

1. 留下總指數與大類

2. 計算年物價上漲率
    算出總指數與所有大類，每一期的上漲率

3. 計算相關係數
    用2.的結果計算，總指數與其他大類成長率的相關係數(可用`cor(x,y)`)

參考  :  https://github.com/tpemartin/109-2-app101/blob/main/weekly_progress/cpi.Rmd
@Simmonslin @yuhong69 @jilufu @chao87119 @want180

**Comment by schaof** [comment]
https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/cpi.R#L16

**Comment by yuhong69** [comment]
https://github.com/yuhong69/109-2-app101/blob/main/weekly_progress/yuhong/06-10-cpi.Rmd

有得到士賢協助，across 前要先轉成 data frame。

**Comment by Simmonslin** [comment]
https://github.com/Simmonslin/109-2-app101/blob/main/weekly_progress/Simmons/cpi.R

**Comment by jilufu** [comment]
https://github.com/jilufu/109-2-app101/blob/5335adad8e220f85c26c37b4d367babcb7e7c4c0/weekly_progress/jilu/cpi.Rmd#L50

**Comment by want180** [comment]
https://github.com/want180/109-2-app101/blob/main/weekly_progress/want180/cpi.Rmd

**Comment by tpemartin** [comment]
- software lifecycle: <https://lifecycle.r-lib.org/articles/stages.html#superseded>
-
